import pandas as pd
import json

# Your data
data_json = """
[
    {"id": "sf-block", "name": "SF Block", "match": "dept of it", "floor": "tagged", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "dept of cse", "floor": "tagged", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "dept of aiml", "floor": "tagged", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "SF Block", "floor": "tagged", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "school of computing", "floor": "tagged", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "sunflower block", "floor": "tagged", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "IT 001", "floor": "Base Floor", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "IT 002", "floor": "Base Floor", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "IT 003", "floor": "Base Floor", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "IT Seminar Hall", "floor": "Base Floor", "floor_no": 0},
    {"id": "sf-block", "name": "SF Block", "match": "IT 101", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block", "name": "SF Block", "match": "IT 102", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block", "name": "SF Block", "match": "Department of Information Technology", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block", "name": "SF Block", "match": "Artificial Intelligence Lab (AI Lab)", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block", "name": "SF Block", "match": "CS 201", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block", "name": "SF Block", "match": "CS 202 💞", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block", "name": "SF Block", "match": "CS 203", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block", "name": "SF Block", "match": "Department of Computer Science and Engineering", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block", "name": "SF Block", "match": "CSE Lab 1", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block", "name": "SF Block", "match": "AIML 101", "floor": "Second Floor", "floor_no": 3},
    {"id": "sf-block", "name": "SF Block", "match": "CS 302", "floor": "Second Floor", "floor_no": 3},
    {"id": "sf-block", "name": "SF Block", "match": "CS 303", "floor": "Second Floor", "floor_no": 3},
    {"id": "sf-block", "name": "SF Block", "match": "Auditorium", "floor": "Second Floor", "floor_no": 3},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "Civil Practical Labs", "floor": "Base Floor", "floor_no": 0},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "Data Mining Lab", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "Cloud Computing Lab", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "DBMS Lab", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "Faculty Hall 5", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "Faculty Hall 7", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "Programming Lab", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "sunflower block", "floor": "Ground Floor", "floor_no": 1},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "CSE Lab 2", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "CSE Lab 3 (Networking Lab)", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "Faculty Hall 5", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "CSE Lab 4 (Web Technology Lab)", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "CSE Lab 5 (Open Source Lab)", "floor": "First Floor", "floor_no": 2},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "Department of Artificial Intelligence and Machine Learning", "floor": "Second Floor", "floor_no": 3},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "CSE Lab 6", "floor": "Second Floor", "floor_no": 3},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "CSE Lab 7 (Data Structure Lab 7)", "floor": "Second Floor", "floor_no": 3},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "CSE Lab 8", "floor": "Second Floor", "floor_no": 3},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "CSE Lab 9", "floor": "Second Floor", "floor_no": 3},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "Faculty Hall 10", "floor": "Second Floor", "floor_no": 3},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "school of mechanics", "floor": "tagged", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "dept of mech", "floor": "tagged", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "dept of aero", "floor": "tagged", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "dept of agri", "floor": "tagged", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Department of Mechanical Engineering", "floor": "Ground Floor", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Department office (Mech)", "floor": "Ground Floor", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Department Library (Mech)", "floor": "Ground Floor", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Smart class room", "floor": "Ground Floor", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Reprography Center", "floor": "Ground Floor", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Cyber Security Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Department of Mechanics", "floor": "First Floor", "floor_no": 1},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Mathematics Experience Centre (ME 101)", "floor": "First Floor", "floor_no": 1},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 102", "floor": "First Floor", "floor_no": 1},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 103", "floor": "First Floor", "floor_no": 1},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 104", "floor": "First Floor", "floor_no": 1},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 105", "floor": "First Floor", "floor_no": 1},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 106", "floor": "First Floor", "floor_no": 1},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 107", "floor": "First Floor", "floor_no": 1},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 108", "floor": "First Floor", "floor_no": 1},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Department of Aeronautical", "floor": "Second Floor", "floor_no": 2},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 201", "floor": "Second Floor", "floor_no": 2},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 202", "floor": "Second Floor", "floor_no": 2},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 203", "floor": "Second Floor", "floor_no": 2},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 204", "floor": "Second Floor", "floor_no": 2},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 205", "floor": "Second Floor", "floor_no": 2},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 206", "floor": "Second Floor", "floor_no": 2},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Faculty Hall 1", "floor": "Second Floor", "floor_no": 2},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Department of Agriculture", "floor": "Third Floor", "floor_no": 3},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 301", "floor": "Third Floor", "floor_no": 3},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 302", "floor": "Third Floor", "floor_no": 3},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 303", "floor": "Third Floor", "floor_no": 3},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 304", "floor": "Third Floor", "floor_no": 3},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 305", "floor": "Third Floor", "floor_no": 3},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "ME 306", "floor": "Third Floor", "floor_no": 3},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Faculty Hall  2", "floor": "Third Floor", "floor_no": 3},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "dept of mech", "floor": "tagged", "floor_no": 0},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Basic Workshop", "floor": "Base Floor", "floor_no": 0},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Inventory Area", "floor": "Base Floor", "floor_no": 0},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Special Machinery Shop", "floor": "Ground floor", "floor_no": 1},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Strength of Materials Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Lathe Shop", "floor": "Ground floor", "floor_no": 1},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Meteorology Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Aqua Sub BIT research center", "floor": "Ground floor", "floor_no": 1},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Fluid Mechanics", "floor": "Ground floor", "floor_no": 1},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Thermal Engineering lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Non-Destructive Testing Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Sensor and Instrumentation lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "MEMS Laboratory", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Mechatronics Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "BIT - Harita Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Sew Eurodrive Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Kinematics \u0026 Dynamic Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Metallurgy Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Aircraft Structure Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Avionics Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Basic Workshop", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Industrial and Mobile Robotics Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "CAM Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "FANUC centre for FOR CNC Machine", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "BIT - FESTO Centre", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "CAD Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Heat Transfer Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Industrial Safety Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Energy Management Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Automative Components Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Smart Agriculture Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Drawing Hall 1", "floor": "Second Floor", "floor_no": 3},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Drawing Hall 2", "floor": "Second Floor", "floor_no": 3},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Fundamentals of Mechanical Engg Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Statics Laboratory", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-left", "name": "AS Block", "match": "Special Labs", "floor": "tagged", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "Dept of ISE", "floor": "tagged", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "AS Block", "floor": "tagged", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "CS 109", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "New Product Development Lab (CS 110)", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "Digital Marketing Lab (CS 111)", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "Research Lab (CS 112)", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "Test and Repair Centre", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "Industrial Design Studio", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "IT Operations", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "Department of Information Science and Technology", "floor": "First floor", "floor_no": 1},
    {"id": "as-main-left", "name": "AS Block", "match": "ISE Lab 1", "floor": "First floor", "floor_no": 1},
    {"id": "as-main-left", "name": "AS Block", "match": "ISE Lab 2", "floor": "First floor", "floor_no": 1},
    {"id": "as-main-left", "name": "AS Block", "match": "Server Room", "floor": "First floor", "floor_no": 1},
    {"id": "as-main-left", "name": "AS Block", "match": "Faculty Hall 1", "floor": "First floor", "floor_no": 1},
    {"id": "as-main-left", "name": "AS Block", "match": "Robotics \u0026 Automation Lab", "floor": "First floor", "floor_no": 1},
    {"id": "as-main-left", "name": "AS Block", "match": "BT Lab", "floor": "First floor", "floor_no": 1},
    {"id": "as-main-left", "name": "AS Block", "match": "Discussion Room", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Conference Room", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Data Science Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Open Source Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "AR/VR Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Design \u0026 Prototyping Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Hackathon Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Integrated AI Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Sensor Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Vision Engineering Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Embedded Systems Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "UAV Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "UUV Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Robotics Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-left", "name": "AS Block", "match": "Automation Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-main-right", "name": "Special Labs", "match": "Special Labs", "floor": "tagged", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "Dept of CSBS", "floor": "tagged", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "AS Block", "floor": "tagged", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "Manufacturing and Fabrication Lab", "floor": "Base Floor", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "Hybrid Human Powered Vehicle", "floor": "Base Floor", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "Agricultural Vehicle", "floor": "Base Floor", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "On Road Off Road Vehicle", "floor": "Base Floor", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "MF Lab", "floor": "Base Floor", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "Sustainable Civil Engineering Materials Lab", "floor": "Base Floor", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "Kart Vehicle", "floor": "Base Floor", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "Electrical Vehicle", "floor": "Base Floor", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "Reprographic Centre", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "CB 101", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "Electronic System for Wildlife Conservation Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "Virtual Instrumentation Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "Block Chain Technology Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "Product Innovation Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "Intelligence Innovation Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "Natural Language Processing (NLP) Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "Power Conversion and System Integration Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "Signal Processing for Health Care Lab", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "World Skill Training Centre", "floor": "Ground floor", "floor_no": 1},
    {"id": "as-main-right", "name": "Special Labs", "match": "Department of Computer Science and Business System", "floor": "First Floor", "floor_no": 2},
    {"id": "as-main-right", "name": "Special Labs", "match": "CSBS Lab 1", "floor": "First Floor", "floor_no": 2},
    {"id": "as-main-right", "name": "Special Labs", "match": "CSBS Lab 2", "floor": "First Floor", "floor_no": 2},
    {"id": "as-main-right", "name": "Special Labs", "match": "CSBS Lab 3", "floor": "First Floor", "floor_no": 2},
    {"id": "as-main-right", "name": "Special Labs", "match": "Mathematics Experience Centre", "floor": "First Floor", "floor_no": 2},
    {"id": "as-main-right", "name": "Special Labs", "match": "Embedded Technology Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "as-main-right", "name": "Special Labs", "match": "Energy and Thermal Product Development Lab", "floor": "First Floor", "floor_no": 2},
    {"id": "as-main-right", "name": "Special Labs", "match": "Internet of Things (IoT) Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Cloud Computing Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Data Science Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Electrical Product Development Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Next Generation Networking Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Communication \u0026 Protocol Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Energy Storage \u0026 Conversion Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Micro Prototyping Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Robotics Division", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Drone division", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "3D printing Division", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "AI Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-main-right", "name": "Special Labs", "match": "Mobile and Web App Dev Lab", "floor": "Second Floor", "floor_no": 3},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "Dept of Biomedical", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "Department of Biomedical Engineering", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "EW 113", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "EW 114", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "EW 115", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "EW 213", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "EW 214", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "EW 215", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "Dept of Chemistry", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "Department of Chemistry", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "Chemistry Laboratory - 1", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "Language Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "ELCC Cell", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "Faculty Hall", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "Physics Laboratory - 1", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "Faculty Hall", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "Dept of Civil", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "Department of Civil Engineering", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "Conference Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "EW 116", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "EW 117", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "EW 118", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "EW 216", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "EW 217", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "EW 218", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "Dept of of physics", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "Signal Processing Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "PCB Design Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "PCB Fabrication Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "Department of Physics", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "Physics Laboratory - 2", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "Faculty  Hall", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "Chemistry Laboratory - 2", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "Faculty Hall", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-5", "name": "AS rib 5", "match": "Dept of ECE", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-5", "name": "AS rib 5", "match": "Faculty Hall 2", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-5", "name": "AS rib 5", "match": "EW 107", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-5", "name": "AS rib 5", "match": "EW 108 ❤️‍🩹", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-5", "name": "AS rib 5", "match": "EW 109", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-5", "name": "AS rib 5", "match": "EW 207", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-5", "name": "AS rib 5", "match": "EW 208", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-5", "name": "AS rib 5", "match": "EW 209", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-6", "name": "AS rib 6", "match": "Dept of Civil", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-6", "name": "AS rib 6", "match": "Dept of biomedical", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-6", "name": "AS rib 6", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-6", "name": "AS rib 6", "match": "Soil Mechanic Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-6", "name": "AS rib 6", "match": "CADD \u0026 Survey Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-6", "name": "AS rib 6", "match": "Survey \u0026 Environmental Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-6", "name": "AS rib 6", "match": "Biochemistry Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-6", "name": "AS rib 6", "match": "Physiology Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "Dept of ECE", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "Department of Electrical and Communication Engineering", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "Faculty Hall 1", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "ECE Seminar Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "Faculty Hall 3", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "EW 111", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "EW 112", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "EW 210", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "EW 211", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "EW 212", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-8", "name": "AS rib 8", "match": "Dept of ECE", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-8", "name": "AS rib 8", "match": "Analog electronic \u0026 IC Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-8", "name": "AS rib 8", "match": "Advanced Communication System Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-8", "name": "AS rib 8", "match": "Network Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-8", "name": "AS rib 8", "match": "PG VLSI Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-8", "name": "AS rib 8", "match": "Product Development Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-8", "name": "AS rib 8", "match": "Analog \u0026 Digital Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-8", "name": "AS rib 8", "match": "Microwave \u0026 Optical Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "Dept of food Tech", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "FD", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "Department of Food Technology", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "EW 101", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "EW 102", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "EW 103", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "EW 201", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "EW 202", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "EW 203", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-10", "name": "AS rib 10", "match": "Chemical Processing Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-10", "name": "AS rib 10", "match": "Apparel Testing Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-10", "name": "AS rib 10", "match": "Textile Testing Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-10", "name": "AS rib 10", "match": "Faculty Hall", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-10", "name": "AS rib 10", "match": "VLSI Design Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-10", "name": "AS rib 10", "match": "Digital Electronic Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-10", "name": "AS rib 10", "match": "Microprocessor \u0026 Microcontroller Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "Dept of Textile Tech", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "TX", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "Department of Textile Technology", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "Textile Seminar Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "EW 104", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "EW 105", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "EW 106", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "EW 204", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "EW 205", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "EW 206", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-12", "name": "AS rib 12", "match": "Weaving and Knitting Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "as-rib-12", "name": "AS rib 12", "match": "Food Technology Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "as-rib-12", "name": "AS rib 12", "match": "Food Analysis and Instrumentation Facility", "floor": "Second Floor", "floor_no": 2},
    {"id": "as-rib-12", "name": "AS rib 12", "match": "Food Technology Lab - 2", "floor": "Second Floor", "floor_no": 2},
    {"id": "fashion-centre", "name": "Fashion Resource Centre", "match": "Dept of Fashion Tech", "floor": "tagged", "floor_no": 0},
    {"id": "fashion-centre", "name": "Fashion Resource Centre", "match": "FT", "floor": "tagged", "floor_no": 0},
    {"id": "fashion-centre", "name": "Fashion Resource Centre", "match": "Department of Fashion Technology", "floor": "Ground Floor", "floor_no": 0},
    {"id": "fashion-centre", "name": "Fashion Resource Centre", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "fashion-centre", "name": "Fashion Resource Centre", "match": "Class rooms", "floor": "First Floor", "floor_no": 1},
    {"id": "fashion-centre", "name": "Fashion Resource Centre", "match": "Garment Construction Lab 1", "floor": "First Floor", "floor_no": 1},
    {"id": "fashion-centre", "name": "Fashion Resource Centre", "match": "Garment Construction Lab 2", "floor": "First Floor", "floor_no": 1},
    {"id": "spinning-lab", "name": "Spinning Lab", "match": "Spinning Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "spinning-lab", "name": "Spinning Lab", "match": "Spinning Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-1", "name": "IB Block", "match": "Dept of maths", "floor": "tagged", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "Dept of Bio-Tech", "floor": "tagged", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "Department of Mathematics", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "IB 101 (left as it is in remainder of old names)", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "WW 002", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "WW 003", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "WW 004", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "Maths Faculty Hall - 1", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "Maths Faculty Hall - 2", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "Biotech Seminar Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block", "match": "Genetic Engineering Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-1", "name": "IB Block", "match": "Molecular Biology Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-1", "name": "IB Block", "match": "Bio-polymer Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-1", "name": "IB Block", "match": "Bio Material Synthesis and Analysis Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-1", "name": "IB Block", "match": "Bio-prospecting Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-1", "name": "IB Block", "match": "Department of Bio-Technology", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-1", "name": "IB Block", "match": "Plant Issue Culture Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-1", "name": "IB Block", "match": "Faculty Hall", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-1", "name": "IB Block", "match": "WW 216", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-1", "name": "IB Block", "match": "WW 217", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-1", "name": "IB Block", "match": "WW 218", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-1", "name": "IB Block", "match": "WW 219", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-1", "name": "IB Block", "match": "WW 220", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-1", "name": "IB Block", "match": "WW 221", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-1", "name": "IB Block", "match": "Maths Faculty Hall - 5", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-2", "name": "IB Block", "match": "Dept of Bio-Tech", "floor": "tagged", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 005", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 006", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 007", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 008", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 010", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 011", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 012", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "Bio-process and Bio-product Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "BIT Integrated Plant Research Facility", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "Bio Energy Research Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block", "match": "Fungal Bio-diversity and Bio-resources Research Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Lecture Hall IB 118", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Nano Biotechnology Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Molecular Diagnostic and Bacterial Pathogenemis Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Downstream Processing Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Cell Biology Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Microbiology Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Chemical Engineering Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Bio Process Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Bio Separation Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Fume Head Room", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Bio-Organic Chemistry Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Instrumental method of analysis Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "Immunology Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 222", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 223", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 224", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 225", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 226", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-2", "name": "IB Block", "match": "WW 227", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-block-2", "name": "IB Block", "match": "Maths Faculty Hall - 6", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "Dept of EIE", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "Department of Electronics and Instrumentation Engineering", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "Yoga Centre", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "WW 113", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "WW 114", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "WW 115", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "WW 212", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "WW 211", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Technology Business Incubator - BIT TBI", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "ß,α cave", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Repository", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Idea Pad", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Mission Control", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Pageant Theatre", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Proto Lounge", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Fab Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Venture Space", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Mentor Studio", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "Launch Pad", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "Dept of AIDS", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "Department of Artificial Intelligence and Data Science", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "CT \u0026 AIDS Library", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "MNC", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "WW 117", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "WW 118", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "CT Faculty Hall 4", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "WW 213", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "WW 214", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "WW 215", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "Dept of CT", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "Dept of AIDS", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "Centre of Excellence in Industrial Automation", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "Internet of Things Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "ZSN Computech", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "E-yantra Robotics Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "Department of Computer Technology", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "CT Labs", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "Department of Artificial Intelligence and Data Science", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "AIDS Labs", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "Dept of EEE", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "Department of Electrical and Electronics Engineering", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "EEE Seminar Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "WW 107", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "WW 108", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "WW 109", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "WW 207", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "WW 206", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-6", "name": "IB rib 6", "match": "Dept of EIE", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-6", "name": "IB rib 6", "match": "EIE Computer Centre", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-6", "name": "IB rib 6", "match": "Process Control Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-6", "name": "IB rib 6", "match": "Sensor and Transducer Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-6", "name": "IB rib 6", "match": "Industrial Instrumentation Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-6", "name": "IB rib 6", "match": "Electronics Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-6", "name": "IB rib 6", "match": "Conference Hall - EIE", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-6", "name": "IB rib 6", "match": "Smart Class Room - EIE", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-7", "name": "IB rib 7", "match": "Dept of EEE", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-7", "name": "IB rib 7", "match": "Faculty Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-7", "name": "IB rib 7", "match": "WW 110", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-7", "name": "IB rib 7", "match": "WW 111", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-7", "name": "IB rib 7", "match": "WW 112", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-7", "name": "IB rib 7", "match": "WW 208", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-7", "name": "IB rib 7", "match": "WW 209", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-7", "name": "IB rib 7", "match": "WW 210", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-8", "name": "IB rib 8", "match": "BIT - Gurugualam", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-8", "name": "IB rib 8", "match": "Electronics Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-8", "name": "IB rib 8", "match": "Electronics Machines Lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-8", "name": "IB rib 8", "match": "Faculty Hall", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-8", "name": "IB rib 8", "match": "Power Electronics and Drives Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-9", "name": "IB rib 9", "match": "Xerox printout", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-9", "name": "IB rib 9", "match": "Seminar Hall Mech", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-9", "name": "IB rib 9", "match": "WW 101", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-9", "name": "IB rib 9", "match": "WW 102", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-9", "name": "IB rib 9", "match": "WW 103", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-9", "name": "IB rib 9", "match": "WW 201", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-9", "name": "IB rib 9", "match": "WW 202", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-10", "name": "IB rib 10", "match": "Dept of EEE", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-10", "name": "IB rib 10", "match": "BIT Gurugualam", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-10", "name": "IB rib 10", "match": "Faculty Hall", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-10", "name": "IB rib 10", "match": "EEE Computer Centre", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-10", "name": "IB rib 10", "match": "Store Room", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-10", "name": "IB rib 10", "match": "EEE Tutorial Hall", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-11", "name": "IB rib 11", "match": "Department of Humanities", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-11", "name": "IB rib 11", "match": "Chairman Cabin", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-11", "name": "IB rib 11", "match": "WW 104 💝", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-11", "name": "IB rib 11", "match": "WW 105", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-11", "name": "IB rib 11", "match": "WW 106", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-11", "name": "IB rib 11", "match": "WW 203", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-11", "name": "IB rib 11", "match": "WW 204", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-11", "name": "IB rib 11", "match": "WW 205", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-12", "name": "IB rib 12", "match": "BIT Gurugualam", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-12", "name": "IB rib 12", "match": "Wielding and pm lab", "floor": "Ground Floor", "floor_no": 0},
    {"id": "ib-rib-12", "name": "IB rib 12", "match": "Home Appliances Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-12", "name": "IB rib 12", "match": "Salzar BIT Innovation Centre", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-12", "name": "IB rib 12", "match": "Basic EEE Lab", "floor": "First Floor", "floor_no": 1},
    {"id": "ib-rib-12", "name": "IB rib 12", "match": "PLC Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-12", "name": "IB rib 12", "match": "A\u0026D Lab", "floor": "Second Floor", "floor_no": 2},
    {"id": "ib-rib-12", "name": "IB rib 12", "match": "Thermal Drawing Hall", "floor": "Second Floor", "floor_no": 2},
    {"id": "internet-centre", "name": "Internet Centre", "match": "COE", "floor": "tagged", "floor_no": 0},
    {"id": "internet-centre", "name": "Internet Centre", "match": "Chrome OS", "floor": "tagged", "floor_no": 0},
    {"id": "internet-centre", "name": "Internet Centre", "match": "Internet Centre", "floor": "Ground Floor", "floor_no": 0},
    {"id": "internet-centre", "name": "Internet Centre", "match": "Controller of Examination (COE)", "floor": "First Floor", "floor_no": 1},
    {"id": "placement-and-training", "name": "Placement and Training Cell", "match": "", "floor": "tagged", "floor_no": 0},
    {"id": "placement-and-training", "name": "Placement and Training Cell", "match": "Department of Training and Placement", "floor": "Ground Floor", "floor_no": 0},
    {"id": "placement-and-training", "name": "Placement and Training Cell", "match": "Vedhanayagam Auditorium", "floor": "First Floor", "floor_no": 1},
    {"id": "indoor-gym", "name": "Gym", "match": "", "floor": "tagged", "floor_no": 0},
    {"id": "indoor-gym", "name": "Gym", "match": "Hostel Manager Cabin", "floor": "Ground Floor", "floor_no": 0},
    {"id": "indoor-gym", "name": "Gym", "match": "Boys Gym", "floor": "First Floor", "floor_no": 1},
    {"id": "indoor-gym", "name": "Gym", "match": "Yoga Centre", "floor": "Second Floor", "floor_no": 2},
    {"id": "boys-visitor-hall", "name": "Visitor hall (Boys)", "match": "", "floor": "tagged", "floor_no": 0},
    {"id": "boys-visitor-hall", "name": "Visitor hall (Boys)", "match": "Boys Visitor Hall", "floor": "Ground Floor", "floor_no": 0},
    {"id": "recreation-hall", "name": "Recreation Hall", "match": "shop", "floor": "tagged", "floor_no": 0},
    {"id": "recreation-hall", "name": "Recreation Hall", "match": "store", "floor": "tagged", "floor_no": 0},
    {"id": "recreation-hall", "name": "Recreation Hall", "match": "gift", "floor": "tagged", "floor_no": 0},
    {"id": "recreation-hall", "name": "Recreation Hall", "match": "mobile", "floor": "tagged", "floor_no": 0},
    {"id": "recreation-hall", "name": "Recreation Hall", "match": "Conventional Store", "floor": "Ground Floor", "floor_no": 0},
    {"id": "recreation-hall", "name": "Recreation Hall", "match": "Gift Shop", "floor": "Ground Floor", "floor_no": 0},
    {"id": "recreation-hall", "name": "Recreation Hall", "match": "Mobile Shop", "floor": "Ground Floor", "floor_no": 0},
    {"id": "recreation-hall", "name": "Recreation Hall", "match": "Recreation Hall", "floor": "First Floor", "floor_no": 1},
    {"id": "girls-mess", "name": "Mess", "match": "Mess", "floor": "Ground Floor", "floor_no": 0},
    {"id": "girls-mess", "name": "Mess", "match": "Dance Hall", "floor": "First Floor", "floor_no": 1},
    {"id": "girls-mess", "name": "Mess", "match": "Girls Gym", "floor": "First Floor", "floor_no": 1},
    {"id": "girls-mess", "name": "Mess", "match": "Mess", "floor": "First Floor", "floor_no": 1},
    {"id": "sf-block", "name": "SF Block", "match": "SF Block", "floor": "tagged", "floor_no": 0},
    {"id": "sf-block-labs", "name": "SF Block Labs", "match": "SF Block Labs", "floor": "tagged", "floor_no": 0},
    {"id": "mechanic-front", "name": "Mech Block Entrance", "match": "Mech Block Entrance", "floor": "tagged", "floor_no": 0},
    {"id": "mechanic-back", "name": "Mechanic Block", "match": "Mechanic Block", "floor": "tagged", "floor_no": 0},
    {"id": "as-main-left", "name": "AS Block", "match": "AS Block", "floor": "tagged", "floor_no": 0},
    {"id": "as-main-right", "name": "Special Labs", "match": "Special Labs", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-1", "name": "AS rib 1", "match": "AS rib 1", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-3", "name": "AS rib 3", "match": "AS rib 3", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-5", "name": "AS rib 5", "match": "AS rib 5", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-7", "name": "AS rib 7", "match": "AS rib 7", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-9", "name": "AS rib 9", "match": "AS rib 9", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-11", "name": "AS rib 11", "match": "AS rib 11", "floor": "tagged", "floor_no": 0},
    {"id": "fashion-centre", "name": "Fashion Resource Centre", "match": "Fashion Resource Centre", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-2", "name": "AS rib 2", "match": "AS rib 2", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-4", "name": "AS rib 4", "match": "AS rib 4", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-6", "name": "AS rib 6", "match": "AS rib 6", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-8", "name": "AS rib 8", "match": "AS rib 8", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-10", "name": "AS rib 10", "match": "AS rib 10", "floor": "tagged", "floor_no": 0},
    {"id": "as-rib-12", "name": "AS rib 12", "match": "AS rib 12", "floor": "tagged", "floor_no": 0},
    {"id": "chiller-plant", "name": "Chiller Plant", "match": "Chiller Plant", "floor": "tagged", "floor_no": 0},
    {"id": "spinning-lab", "name": "Spinning Lab", "match": "Spinning Lab", "floor": "tagged", "floor_no": 0},
    {"id": "main-store", "name": "Maintenance \u0026 Stationary Store", "match": "Maintenance \u0026 Stationary Store", "floor": "tagged", "floor_no": 0},
    {"id": "library", "name": "Library", "match": "Library", "floor": "tagged", "floor_no": 0},
    {"id": "main-auditorium", "name": "Main Auditorium", "match": "Main Auditorium", "floor": "tagged", "floor_no": 0},
    {"id": "placement-and-training", "name": "Placement and Training Cell", "match": "Placement and Training Cell", "floor": "tagged", "floor_no": 0},
    {"id": "internet-centre", "name": "Internet Centre", "match": "Internet Centre", "floor": "tagged", "floor_no": 0},
    {"id": "radio", "name": "BIT Community Radio Centre", "match": "BIT Community Radio Centre", "floor": "tagged", "floor_no": 0},
    {"id": "ib-block-1", "name": "IB Block (1)", "match": "IB Block (1)", "floor": "tagged", "floor_no": 0},
    {"id": "ib-block-2", "name": "IB Block (2)", "match": "IB Block (2)", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-1", "name": "IB rib 1", "match": "IB rib 1", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-3", "name": "IB rib 3", "match": "IB rib 3", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-5", "name": "IB rib 5", "match": "IB rib 5", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-7", "name": "IB rib 7", "match": "IB rib 7", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-9", "name": "IB rib 9", "match": "IB rib 9", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-11", "name": "IB rib 11", "match": "IB rib 11", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-2", "name": "IB rib 2", "match": "IB rib 2", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-4", "name": "IB rib 4", "match": "IB rib 4", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-6", "name": "IB rib 6", "match": "IB rib 6", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-8", "name": "IB rib 8", "match": "IB rib 8", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-10", "name": "IB rib 10", "match": "IB rib 10", "floor": "tagged", "floor_no": 0},
    {"id": "ib-rib-12", "name": "IB rib 12", "match": "IB rib 12", "floor": "tagged", "floor_no": 0},
    {"id": "cafeteria", "name": "Cafeteria", "match": "Cafeteria", "floor": "tagged", "floor_no": 0},
    {"id": "boys-mess", "name": "Boys Mess", "match": "Boys Mess", "floor": "tagged", "floor_no": 0},
    {"id": "sapphire", "name": "Sapphire Hostel", "match": "Sapphire Hostel", "floor": "tagged", "floor_no": 0},
    {"id": "ruby", "name": "Ruby Hostel", "match": "Ruby Hostel", "floor": "tagged", "floor_no": 0},
    {"id": "pearl", "name": "Pearl Hostel", "match": "Pearl Hostel", "floor": "tagged", "floor_no": 0},
    {"id": "diamond", "name": "Diamond Hostel", "match": "Diamond Hostel", "floor": "tagged", "floor_no": 0},
    {"id": "emerald", "name": "Emerald Hostel", "match": "Emerald Hostel", "floor": "tagged", "floor_no": 0},
    {"id": "coral", "name": "Coral Hostel (NRI Hostel)", "match": "Coral Hostel (NRI Hostel)", "floor": "tagged", "floor_no": 0},
    {"id": "outdoor-gym", "name": "Outdoor Gym", "match": "Outdoor Gym", "floor": "tagged", "floor_no": 0},
    {"id": "indoor-gym", "name": "Gym", "match": "Gym", "floor": "tagged", "floor_no": 0},
    {"id": "boys-laundry", "name": "Laundry (Boys)", "match": "Laundry (Boys)", "floor": "tagged", "floor_no": 0},
    {"id": "power-house", "name": "Power House", "match": "Power House", "floor": "tagged", "floor_no": 0},
    {"id": "tennis-court-1", "name": "Tennis Court 1", "match": "Tennis Court 1", "floor": "tagged", "floor_no": 0},
    {"id": "tennis-court-2", "name": "Tennis Court 2", "match": "Tennis Court 2", "floor": "tagged", "floor_no": 0},
    {"id": "basket-ball-court", "name": "Basket Ball Court", "match": "Basket Ball Court", "floor": "tagged", "floor_no": 0},
    {"id": "volley-ball-court", "name": "Volley Ball Court", "match": "Volley Ball Court", "floor": "tagged", "floor_no": 0},
    {"id": "playground-1", "name": "Empty Playground", "match": "Empty Playground", "floor": "tagged", "floor_no": 0},
    {"id": "agri-playground", "name": "Agri Playground", "match": "Agri Playground", "floor": "tagged", "floor_no": 0},
    {"id": "dayscholar-mess-1", "name": "Day Scholar Mess", "match": "Day Scholar Mess", "floor": "tagged", "floor_no": 0},
    {"id": "dayscholar-mess-2", "name": "Day Scholar Mess", "match": "Day Scholar Mess", "floor": "tagged", "floor_no": 0},
    {"id": "pet-room", "name": "PET Room", "match": "PET Room", "floor": "tagged", "floor_no": 0},
    {"id": "recreation-hall", "name": "Recreation hall", "match": "Recreation hall", "floor": "tagged", "floor_no": 0},
    {"id": "girls-basketball-court", "name": "Basketball Court", "match": "Basketball Court", "floor": "tagged", "floor_no": 0},
    {"id": "girls-mess", "name": "Girls Mess", "match": "Girls Mess", "floor": "tagged", "floor_no": 0},
    {"id": "kaveri", "name": "Cauvery Hostel", "match": "Cauvery Hostel", "floor": "tagged", "floor_no": 0},
    {"id": "narmadha", "name": "Narmadha Hostel", "match": "Narmadha Hostel", "floor": "tagged", "floor_no": 0},
    {"id": "ganga", "name": "Ganga Hostel", "match": "Ganga Hostel", "floor": "tagged", "floor_no": 0},
    {"id": "yamuna", "name": "Yamuna Hostel", "match": "Yamuna Hostel", "floor": "tagged", "floor_no": 0},
    {"id": "north-bhavani", "name": "North Bhavani", "match": "North Bhavani", "floor": "tagged", "floor_no": 0},
    {"id": "middle-bhavani", "name": "Old Bhavani", "match": "Old Bhavani", "floor": "tagged", "floor_no": 0},
    {"id": "south-bhavani", "name": "South Bhavani", "match": "South Bhavani", "floor": "tagged", "floor_no": 0},
    {"id": "medical-centre", "name": "Medical Centre", "match": "Medical Centre", "floor": "tagged", "floor_no": 0},
    {"id": "west-gate", "name": "West Gate", "match": "West Gate", "floor": "tagged", "floor_no": 0},
    {"id": "cricket-ground", "name": "Cricket Ground", "match": "Cricket Ground", "floor": "tagged", "floor_no": 0},
    {"id": "football-ground", "name": "Football Ground", "match": "Football Ground", "floor": "tagged", "floor_no": 0},
    {"id": "playground-2", "name": "Empty Playgorund", "match": "Empty Playgorund", "floor": "tagged", "floor_no": 0},
    {"id": "playground-3", "name": "Empty Playground", "match": "Empty Playground", "floor": "tagged", "floor_no": 0},
    {"id": "west-parking", "name": "West Parking Lot", "match": "West Parking Lot", "floor": "tagged", "floor_no": 0},
    {"id": "staff-quarters", "name": "Staff Quarters", "match": "Staff Quarters", "floor": "tagged", "floor_no": 0},
    {"id": "smart-agri-fields", "name": "Smart Agri Fields", "match": "Smart Agri Fields", "floor": "tagged", "floor_no": 0},
    {"id": "main-gate", "name": "Main Gate", "match": "Main Gate", "floor": "tagged", "floor_no": 0},
    {"id": "main-parking", "name": "Main Parking Area", "match": "Main Parking Area", "floor": "tagged", "floor_no": 0},
    {"id": "principal-office", "name": "Principal Office", "match": "Principal Office", "floor": "tagged", "floor_no": 0},
    {"id": "lake", "name": "Lake", "match": "Lake", "floor": "tagged", "floor_no": 0},
    {"id": "research-park", "name": "Research Park", "match": "Research Park", "floor": "tagged", "floor_no": 0},
    {"id": "guest-house", "name": "BIT Guest House", "match": "BIT Guest House", "floor": "tagged", "floor_no": 0},
    {"id": "bus", "name": "Day Scholar Buses", "match": "Day Scholar Buses", "floor": "tagged", "floor_no": 0},
    {"id": "herbal-garden", "name": "Herbal Garden", "match": "Herbal Garden", "floor": "tagged", "floor_no": 0},
    {"id": "atm-1", "name": "ATM", "match": "ATM", "floor": "tagged", "floor_no": 0},
    {"id": "west-gate-staffs", "name": "West Gate (Staffs)", "match": "West Gate (Staffs)", "floor": "tagged", "floor_no": 0},
    {"id": "principal-room", "name": "Principal Cabin", "match": "Principal Cabin", "floor": "tagged", "floor_no": 0},
    {"id": "dean-room", "name": "Dean Cabin", "match": "Dean Cabin", "floor": "tagged", "floor_no": 0},
    {"id": "boys-visitor-hall", "name": "Visitor Hall (Boys)", "match": "Visitor Hall (Boys)", "floor": "tagged", "floor_no": 0},
    {"id": "boys-hostels", "name": "Boys Hostels", "match": "Boys Hostels", "floor": "tagged", "floor_no": 0},
    {"id": "boys-canteen", "name": "Canteens (boys)", "match": "Canteens (boys)", "floor": "tagged", "floor_no": 0},
    {"id": "girls-hostels", "name": "Girls Hostels", "match": "Girls Hostels", "floor": "tagged", "floor_no": 0},
    {"id": "girls-visitor-hut", "name": "Visitors Hut (Girls)", "match": "Visitors Hut (Girls)", "floor": "tagged", "floor_no": 0},
    {"id": "parlour-boys", "name": "Parlour (Boys)", "match": "Parlour (Boys)", "floor": "tagged", "floor_no": 0},
    {"id": "canteen-girls", "name": "Canteen (Girls)", "match": "Canteen (Girls)", "floor": "tagged", "floor_no": 0},
    {"id": "laundry-girls", "name": "Laundry (Girls)", "match": "Laundry (Girls)", "floor": "tagged", "floor_no": 0},
    {"id": "parlour-girls", "name": "Parlour (Girls)", "match": "Parlour (Girls)", "floor": "tagged", "floor_no": 0},
    {"id": "outdoor-gym-2", "name": "Outdoor Gym", "match": "Outdoor Gym", "floor": "tagged", "floor_no": 0},
    {"id": "outdoor-gym-3", "name": "Outdoor Gym", "match": "Outdoor Gym", "floor": "tagged", "floor_no": 0},
    {"id": "throwball-court-girls", "name": "Throw Ball Court", "match": "Throw Ball Court", "floor": "tagged", "floor_no": 0},
    {"id": "volleyball-court-girls", "name": "Volley Ball Court", "match": "Volley Ball Court", "floor": "tagged", "floor_no": 0},
    {"id": "girls-gym", "name": "Girls Gym", "match": "Girls Gym", "floor": "tagged", "floor_no": 0},
    {"id": "dance-hall", "name": "Dance Hall", "match": "Dance Hall", "floor": "tagged", "floor_no": 0}
]
"""

# Load data and fix common encoding/typo issues
data = json.loads(data_json)
for entry in data:
    if "match" in entry:
        # Fix encoding issues like "\u0026"
        entry["match"] = entry["match"].replace("u0026", "&").replace("&", "&")
        # Fix known typo
        if "Playgorund" in entry["match"]:
            entry["match"] = entry["match"].replace("Playgorund", "Playground")
        if "Wielding" in entry["match"]:
             entry["match"] = entry["match"].replace("Wielding", "Welding")

# Create DataFrame
df = pd.DataFrame(data)

# Save to Excel
df.to_excel("campus_data.xlsx", index=False)
print("File 'campus_data.xlsx' has been created successfully!")