import React, { useState, useEffect } from 'react';
import api from '../utils/api';
import { Calendar as CalendarIcon, Download, Check } from 'lucide-react';

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const TimetableResults = ({ timetableId }) => {
    const [entries, setEntries] = useState([]);
    const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
    const hours = Array.from({ length: 8 }, (_, i) => i + 9); // 9 AM to 4 PM

    useEffect(() => {
        if (timetableId) fetchTimetable();
    }, [timetableId]);

    const fetchTimetable = async () => {
        try {
            const res = await api.get(`/timetable/${timetableId}`);
            setEntries(res.data);
        } catch (err) {
            console.error(err);
        }
    };

    const getEntry = (day, hour) => {
        return entries.find(e => e.day === day && e.start_time === hour);
    };

    const exportPDF = () => {
        try {
            const doc = new jsPDF('l', 'mm', 'a4');

            doc.setFontSize(20);
            doc.text(`Timetable: ${timetableId || 'Draft'}`, 14, 22);

            const tableData = hours.map(hour => {
                const row = [`${hour}:00 - ${hour + 1}:00`];
                days.forEach(day => {
                    const entry = getEntry(day, hour);
                    if (entry) {
                        // Safe navigation for nested properties
                        const subject = entry.subject?.name || 'Subject';
                        const faculty = entry.faculty?.name || 'Faculty';
                        const room = entry.room?.room_name || 'Room';
                        row.push(`${subject}\n(${faculty})\n${room}`);
                    } else {
                        row.push("-");
                    }
                });
                return row;
            });

            autoTable(doc, {
                head: [['Time', ...days]],
                body: tableData,
                startY: 30,
                styles: { fontSize: 10, cellPadding: 3 },
                headStyles: { fillColor: [79, 70, 229] },
                theme: 'grid'
            });

            doc.save(`timetable-${timetableId || 'export'}.pdf`);
        } catch (err) {
            console.error("PDF Export Error:", err);
            alert("Failed to export PDF. Please check console.");
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                <div>
                    <h3 className="text-xl font-bold flex items-center gap-2">
                        <Check className="text-green-500" size={24} />
                        Optimized Timetable: {timetableId}
                    </h3>
                    <p className="text-slate-500 text-sm">Generated by AI with 0 clashing constraints</p>
                </div>
                <button
                    onClick={exportPDF}
                    className="flex items-center gap-2 px-4 py-2 border border-slate-200 rounded-xl hover:bg-slate-50 transition-all font-medium"
                >
                    <Download size={18} />
                    Export PDF
                </button>
            </div>

            <div className="overflow-x-auto bg-white rounded-2xl border border-slate-200 shadow-xl">
                <table className="w-full border-collapse">
                    <thead>
                        <tr>
                            <th className="p-4 border-b border-r border-slate-200 bg-slate-50 w-24">Time</th>
                            {days.map(day => (
                                <th key={day} className="p-4 border-b border-slate-200 bg-slate-50 font-bold min-w-[200px]">{day}</th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {hours.map(hour => (
                            <tr key={hour}>
                                <td className="p-4 border-r border-b border-slate-200 bg-slate-50 text-center font-semibold text-slate-500 text-sm">
                                    {hour}:00
                                </td>
                                {days.map(day => {
                                    const entry = getEntry(day, hour);
                                    return (
                                        <td key={day} className="p-2 border-r border-b border-slate-200">
                                            {entry ? (
                                                <div className="bg-primary-50 border-l-4 border-primary-500 p-3 rounded-r-lg">
                                                    <p className="font-bold text-primary-900 text-sm">{entry.subject?.name || 'Subject'}</p>
                                                    <p className="text-xs text-primary-700">{entry.faculty?.name || 'Faculty'}</p>
                                                    <p className="text-[10px] text-primary-600 mt-1 uppercase font-bold">{entry.room?.room_name || 'Room'}</p>
                                                </div>
                                            ) : (
                                                <div className="h-20 bg-slate-50/30 rounded-lg border-2 border-dashed border-slate-100 italic text-[10px] text-slate-300 flex items-center justify-center">
                                                    Empty Slot
                                                </div>
                                            )}
                                        </td>
                                    );
                                })}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default TimetableResults;
